#!/usr/bin/python

import random

def create_set(N) :
	set = []
	  
	for i in range(N):
		set.append(random.randint(-10000, 10000))
		
	return set
	
def write_to_file(filename, dataset):
	for data in dataset:
		filename.write(str(data)+"/n")
	
if __name__ == "__main__" :

	sizes = [5, 50, 500, 5000, 50000]
	new = []
	for size in sizes:
		new = create_set(size)
		#send data to new file
		f = open("Datafile_Size_"+str(size), "w")
		write_to_file(f, new)
